---
- name: Play common tasks
  hosts: 127.0.0.1
  connection: local
  become: yes
  gather_facts: no
  vars:
    ENV: "production"
    Platform: "GCP"

#  vars_files:
#    - group_vars/{{ env }}

  roles:
    - role: common
      ENV: ENV
      Platform: Platform
    